name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.test-webflow-next }}

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/webflow_next:latest .
          docker push docker.pkg.github.com/${{ github.repository }}/webflow_next:latest
