name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display current directory contents
        run: ls -la

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/${{ github.repository }}/webflow_next:latest .
          docker push docker.pkg.github.com/${{ github.repository }}/webflow_next:latest
