name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login docker.pkg.github.com -u antocreadev --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest .
          docker push docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest

      # - name: Verify image in GitHub Container Registry
      #   run: docker pull docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest