name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run:d ocker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest .
          docker push docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest

      # - name: Verify image in GitHub Container Registry
      #   run: docker pull docker.pkg.github.com/antocreadev/webflow-devlink-contentful-nextjs/webflow_newt:latest